services:
  - docker:19.03.1-dind

.kaniko-setup:
  before_script:
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(printf "%s:%s" "${DOCKER_USERNAME}" "${DOCKER_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json

stages:
  - build
  - deploy

prod-build:
  extends: .kaniko-setup
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile" --destination "eziotobioli/whatsapp-manager:CI_COMMIT_TAG"
  only:
    refs:
      - tags
  tags:
    - k8s-fizzy

mr-build:
  extends: .kaniko-setup
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile" --destination "eziotobioli/whatsapp-manager:CI_COMMIT_TAG"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  tags:
    - k8s-fizzy

prod-deploy:
  stage: deploy
  trigger:
    include: pipelines/prod.yml
  allow_failure: true

merge-deploy:
  stage: deploy
  trigger:
    include: pipelines/mr.yml
  allow_failure: true


