services:
  - docker:19.03.1-dind

.kaniko-setup:
  before_script:
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(printf "%s:%s" "${DOCKER_USERNAME}" "${DOCKER_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json

#prod-build:
#  extends: .kaniko-setup
#  stage: build
#  image:
#    name: gcr.io/kaniko-project/executor:v1.9.0-debug
#    entrypoint: [""]
#  script:
#    - /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile" --destination "eziotobioli/whatsapp-manager:CI_COMMIT_TAG"
#  only:
#    - tags
#  tags:
#    - k8s-fizzy

merge-deployment:
  stage: deploy
  trigger:
    include: pipelines/mr.yml

#merge-service:
#  extends: .kaniko-setup
#  stage: build
#  image:
#    name: gcr.io/kaniko-project/executor:v1.9.0-debug
#    entrypoint: [""]
#  script:
#    - kubectl config use-context fizzy_soft/whatsapp-manager:fizzy
#    - kubectl apply -f k8s/mr/service.yaml
#  rules:
#    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
#  tags:
#    - k8s-fizzy
#
#merge-ingress:
#  stage: deploy
#  image:
#    name: bitnami/kubectl:latest
#    entrypoint: ['']
#  script:
#    - kubectl config use-context fizzy_soft/whatsapp-manager:fizzy
#    - kubectl apply -f k8s/mr/ingress-mr.yml
#  rules:
#    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
#  tags:
#    - k8s-fizzy

