services:
  - docker:dind

variables:
  ARTIFACT_NAME: "whatsapp-manager"

.docker-setup:
  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

stages:
  - build
  - deploy

merge-build:
  extends: .docker-setup
  stage: build
  image: docker:latest
  script:
    - docker pull eziotobioli/whatsapp-manager:mr-$CI_MERGE_REQUEST_IID || true
    - docker build -t eziotobioli/whatsapp-manager:mr-$CI_MERGE_REQUEST_IID .
    - docker push eziotobioli/whatsapp-manager:mr-$CI_MERGE_REQUEST_IID
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

prod-build:
  extends: .docker-setup
  stage: build
  image: docker:latest
  script:
    - docker build -t eziotobioli/whatsapp-manager:CI_COMMIT_TAG	 .
    - docker push eziotobioli/whatsapp-manager:CI_COMMIT_TAG
  only:
    - tags


merge-deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config use-context fizzy_soft/whatsapp-manager:fizzy
    - TAG=mr-$CI_MERGE_REQUEST_IID
    - sed -i "s/#{IMAGE_TAG}/$TAG/g" k8s/deployment.yaml
    - kubectl apply -f k8s/deployment.yaml
    - kubectl apply -f k8s/service.yaml
    - kubectl apply -f k8s/ingress.yaml
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'


merge-deploy-manual:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config use-context fizzy_soft/whatsapp-manager:fizzy
    - TAG=mr-$CI_MERGE_REQUEST_IID
    - sed -i "s/#{IMAGE_TAG}/$TAG/g" k8s/deployment.yaml
    - kubectl apply -f k8s/deployment.yaml
    - kubectl apply -f k8s/service.yaml
    - kubectl apply -f k8s/ingress.yaml
  when: manual