services:
  - docker:dind

docker_build:
  stage: build
  image: docker:latest
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t eziotobioli/meta-webhook:$CI_COMMIT_SHORT_SHA	 .
    - docker push eziotobioli/meta-webhook:$CI_COMMIT_SHORT_SHA