merge-deployment:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config use-context fizzy_soft/whatsapp-manager:fizzy
    - TAG=mr-$CI_COMMIT_TAG"
    - sed -i "s/#{IMAGE_TAG}/$TAG/g" k8s/mr.yaml
    - kubectl apply -f k8s/mr/deployment.yaml
  rules:
    - changes:
        - k8s/prod.yml
        - src/*
        - Dockerfile
  tags:
    - k8s-fizzy